/**
 * Token Service - JWT token generation and verification.
 * Generated by forge-cli
 *
 * Environment variables:
 *   JWT_SECRET  - Secret key for signing tokens (required)
 *   JWT_EXPIRY  - Token expiration time (default: '24h')
 */

const jwt = require('jsonwebtoken');

// Configuration
const JWT_SECRET = process.env.JWT_SECRET || 'CHANGE_ME_IN_PRODUCTION';
const JWT_EXPIRY = process.env.JWT_EXPIRY || '24h';
const JWT_REFRESH_EXPIRY = process.env.JWT_REFRESH_EXPIRY || '7d';

/**
 * Generate an access token.
 *
 * @param {object} payload - Data to encode in the token
 * @param {string} payload.id - User ID
 * @param {string} payload.email - User email
 * @param {string} payload.role - User role (optional)
 * @returns {string} JWT access token
 */
const generateToken = (payload) => {
    return jwt.sign(
        {
            id: payload.id,
            email: payload.email,
            role: payload.role || 'user',
        },
        JWT_SECRET,
        { expiresIn: JWT_EXPIRY }
    );
};

/**
 * Generate a refresh token.
 *
 * @param {object} payload - Data to encode in the token
 * @returns {string} JWT refresh token
 */
const generateRefreshToken = (payload) => {
    return jwt.sign(
        { id: payload.id, type: 'refresh' },
        JWT_SECRET,
        { expiresIn: JWT_REFRESH_EXPIRY }
    );
};

/**
 * Generate both access and refresh tokens.
 *
 * @param {object} user - User object
 * @returns {{ accessToken: string, refreshToken: string }}
 */
const generateTokenPair = (user) => {
    return {
        accessToken: generateToken(user),
        refreshToken: generateRefreshToken(user),
    };
};

/**
 * Verify and decode a JWT token.
 *
 * @param {string} token - JWT token to verify
 * @returns {object} Decoded token payload
 * @throws {Error} If token is invalid or expired
 */
const verifyToken = (token) => {
    return jwt.verify(token, JWT_SECRET);
};

module.exports = {
    generateToken,
    generateRefreshToken,
    generateTokenPair,
    verifyToken,
};
