package env

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnvVarEntry represents an environment variable to add to .env files.
type EnvVarEntry struct {
	Key         string
	Value       string
	Description string
}

// EnsureEnvFiles ensures both .env and .env.example exist in the given directory.
// Creates them if they don't exist.
func EnsureEnvFiles(projectDir string) error {
	envPath := filepath.Join(projectDir, ".env")
	examplePath := filepath.Join(projectDir, ".env.example")

	// Create .env if it doesn't exist
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		f, err := os.Create(envPath)
		if err != nil {
			return fmt.Errorf("failed to create .env: %w", err)
		}
		f.WriteString("# Environment Variables\n# Generated by forge-cli\n\n")
		f.Close()
	}

	// Create .env.example if it doesn't exist
	if _, err := os.Stat(examplePath); os.IsNotExist(err) {
		f, err := os.Create(examplePath)
		if err != nil {
			return fmt.Errorf("failed to create .env.example: %w", err)
		}
		f.WriteString("# Environment Variables — Example Template\n# Copy this file to .env and fill in the values\n\n")
		f.Close()
	}

	return nil
}

// AppendEnvVars appends environment variables to both .env and .env.example files.
// Skips any variable that already exists in the respective file.
// Returns the number of variables actually added.
func AppendEnvVars(projectDir string, vars []EnvVarEntry) (int, error) {
	envPath := filepath.Join(projectDir, ".env")
	examplePath := filepath.Join(projectDir, ".env.example")

	// Load existing keys from .env
	existingEnv, err := loadEnvKeys(envPath)
	if err != nil {
		return 0, fmt.Errorf("failed to read .env: %w", err)
	}

	// Load existing keys from .env.example
	existingExample, err := loadEnvKeys(examplePath)
	if err != nil {
		return 0, fmt.Errorf("failed to read .env.example: %w", err)
	}

	addedCount := 0

	// Append to .env
	envFile, err := os.OpenFile(envPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return 0, fmt.Errorf("failed to open .env for writing: %w", err)
	}
	defer envFile.Close()

	// Append to .env.example
	exampleFile, err := os.OpenFile(examplePath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return 0, fmt.Errorf("failed to open .env.example for writing: %w", err)
	}
	defer exampleFile.Close()

	for _, v := range vars {
		// Resolve special placeholder values
		actualValue := resolveValue(v.Value)

		// Add to .env (with actual values)
		if !existingEnv[v.Key] {
			if v.Description != "" {
				fmt.Fprintf(envFile, "# %s\n", v.Description)
			}
			fmt.Fprintf(envFile, "%s=%s\n", v.Key, actualValue)
			addedCount++
		}

		// Add to .env.example (with placeholder values)
		if !existingExample[v.Key] {
			if v.Description != "" {
				fmt.Fprintf(exampleFile, "# %s\n", v.Description)
			}
			// Use placeholder for secrets, actual value for non-secrets
			placeholder := getPlaceholder(v.Key, v.Value)
			fmt.Fprintf(exampleFile, "%s=%s\n", v.Key, placeholder)
		}
	}

	return addedCount, nil
}

// GenerateRandomSecret generates a cryptographically secure random hex string.
func GenerateRandomSecret(length int) string {
	bytes := make([]byte, length/2+1)
	if _, err := rand.Read(bytes); err != nil {
		// Fallback to a less secure but functional default
		return strings.Repeat("x", length)
	}
	return hex.EncodeToString(bytes)[:length]
}

// loadEnvKeys reads a .env file and returns a set of existing keys.
func loadEnvKeys(path string) (map[string]bool, error) {
	keys := make(map[string]bool)

	file, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return keys, nil
		}
		return nil, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Extract key from KEY=VALUE
		parts := strings.SplitN(line, "=", 2)
		if len(parts) >= 1 {
			key := strings.TrimSpace(parts[0])
			if key != "" {
				keys[key] = true
			}
		}
	}

	return keys, scanner.Err()
}

// resolveValue resolves special placeholder values like {{RANDOM_SECRET_32}}.
func resolveValue(value string) string {
	switch value {
	case "{{RANDOM_SECRET_32}}":
		return GenerateRandomSecret(32)
	case "{{RANDOM_SECRET_64}}":
		return GenerateRandomSecret(64)
	case "{{RANDOM_SECRET_16}}":
		return GenerateRandomSecret(16)
	default:
		return value
	}
}

// getPlaceholder returns an appropriate placeholder for .env.example.
// Secrets get masked, other values show the default.
func getPlaceholder(key, defaultValue string) string {
	// If it's a random secret placeholder, use a descriptive placeholder
	if strings.Contains(defaultValue, "RANDOM_SECRET") {
		return "<your-secret-key-here>"
	}

	// For non-secret values, use the actual default
	return defaultValue
}
