/**
 * JWT Authentication Middleware for Express.
 * Generated by forge-cli
 *
 * Protects routes by verifying JWT tokens from the Authorization header.
 *
 * Setup:
 *   1. Set JWT_SECRET environment variable
 *   2. Use on protected routes:
 *      const { authMiddleware } = require('./middlewares/authMiddleware');
 *      app.get('/protected', authMiddleware, handler);
 */

const { AppError } = require('../utils/AppError');
const { verifyToken } = require('../services/tokenService');

/**
 * JWT Authentication middleware.
 * Extracts token from Authorization header, verifies it,
 * and attaches the decoded payload to req.user.
 */
const authMiddleware = (req, res, next) => {
    try {
        // Get token from header
        const authHeader = req.headers.authorization;

        if (!authHeader) {
            throw AppError.unauthorized('No authorization header provided');
        }

        // Support "Bearer <token>" format
        const parts = authHeader.split(' ');
        if (parts.length !== 2 || parts[0] !== 'Bearer') {
            throw AppError.unauthorized('Invalid authorization format. Use: Bearer <token>');
        }

        const token = parts[1];

        // Verify token
        const decoded = verifyToken(token);

        // Attach user data to request
        req.user = decoded;

        next();
    } catch (error) {
        if (error instanceof AppError) {
            next(error);
        } else {
            next(AppError.unauthorized('Invalid or expired token'));
        }
    }
};

/**
 * Role-based authorization middleware.
 * Use after authMiddleware to restrict access by role.
 *
 * Usage:
 *   app.get('/admin', authMiddleware, authorize('admin'), handler);
 *   app.get('/manager', authMiddleware, authorize('admin', 'manager'), handler);
 *
 * @param  {...string} roles - Allowed roles
 */
const authorize = (...roles) => {
    return (req, res, next) => {
        if (!req.user) {
            return next(AppError.unauthorized('Authentication required'));
        }

        if (!roles.includes(req.user.role)) {
            return next(
                AppError.forbidden(
                    `Role '${req.user.role}' is not authorized to access this resource`
                )
            );
        }

        next();
    };
};

module.exports = { authMiddleware, authorize };
