/**
 * Global Error Handler Middleware for Express.
 * Generated by forge-cli
 *
 * Setup: Add this AFTER all your routes in app.js:
 *   const { errorHandler } = require('./middlewares/errorHandler');
 *   app.use(errorHandler);
 */

const { AppError } = require('../utils/AppError');

/**
 * Global error handling middleware.
 * Catches all errors thrown in route handlers and middlewares.
 *
 * @param {Error} err - The error object
 * @param {import('express').Request} req - Express request
 * @param {import('express').Response} res - Express response
 * @param {import('express').NextFunction} next - Express next function
 */
const errorHandler = (err, req, res, next) => {
    // Default values
    let statusCode = err.statusCode || 500;
    let message = err.message || 'Internal Server Error';
    let details = null;

    // Handle known AppError instances
    if (err instanceof AppError) {
        statusCode = err.statusCode;
        message = err.message;
        details = err.details;
    }

    // Handle Mongoose/MongoDB validation errors
    if (err.name === 'ValidationError') {
        statusCode = 422;
        message = 'Validation Error';
        details = Object.values(err.errors).map((e) => ({
            field: e.path,
            message: e.message,
        }));
    }

    // Handle Mongoose duplicate key error
    if (err.code === 11000) {
        statusCode = 409;
        message = 'Duplicate field value';
        const field = Object.keys(err.keyValue)[0];
        details = { field, value: err.keyValue[field] };
    }

    // Handle JWT errors
    if (err.name === 'JsonWebTokenError') {
        statusCode = 401;
        message = 'Invalid token';
    }

    if (err.name === 'TokenExpiredError') {
        statusCode = 401;
        message = 'Token expired';
    }

    // Log error (only server errors)
    if (statusCode >= 500) {
        console.error(`[ERROR] ${req.method} ${req.originalUrl}`, {
            statusCode,
            message: err.message,
            stack: err.stack,
        });
    }

    // Send response
    const response = {
        success: false,
        statusCode,
        message,
    };

    // Include details if available
    if (details) {
        response.details = details;
    }

    // Include stack trace in development mode
    if (process.env.NODE_ENV === 'development') {
        response.stack = err.stack;
    }

    res.status(statusCode).json(response);
};

/**
 * 404 Not Found handler.
 * Add BEFORE the errorHandler middleware:
 *   app.use(notFoundHandler);
 *   app.use(errorHandler);
 */
const notFoundHandler = (req, res, next) => {
    next(new AppError(`Route ${req.originalUrl} not found`, 404));
};

module.exports = { errorHandler, notFoundHandler };
