/**
 * Request Logger Middleware for Express.
 * Generated by forge-cli
 *
 * Logs incoming HTTP requests with method, URL, status code,
 * and response time — with color-coded output.
 *
 * Setup: Add this BEFORE your routes in app.js:
 *   const { requestLogger } = require('./middlewares/requestLogger');
 *   app.use(requestLogger);
 */

/**
 * Color codes for terminal output
 */
const colors = {
    reset: '\x1b[0m',
    dim: '\x1b[2m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    red: '\x1b[31m',
    cyan: '\x1b[36m',
    magenta: '\x1b[35m',
    white: '\x1b[37m',
};

/**
 * Get color based on HTTP status code
 */
const getStatusColor = (statusCode) => {
    if (statusCode >= 500) return colors.red;
    if (statusCode >= 400) return colors.yellow;
    if (statusCode >= 300) return colors.cyan;
    if (statusCode >= 200) return colors.green;
    return colors.white;
};

/**
 * Get color based on HTTP method
 */
const getMethodColor = (method) => {
    const methodColors = {
        GET: colors.green,
        POST: colors.cyan,
        PUT: colors.yellow,
        PATCH: colors.yellow,
        DELETE: colors.red,
        OPTIONS: colors.dim,
        HEAD: colors.dim,
    };
    return methodColors[method] || colors.white;
};

/**
 * Format duration in a human-readable way
 */
const formatDuration = (ms) => {
    if (ms < 1) return `${(ms * 1000).toFixed(0)}μs`;
    if (ms < 1000) return `${ms.toFixed(0)}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
};

/**
 * Request logger middleware.
 * Logs: timestamp, method, URL, status code, response time.
 */
const requestLogger = (req, res, next) => {
    const start = process.hrtime.bigint();

    // Capture the original end method
    const originalEnd = res.end;

    res.end = function (...args) {
        const duration = Number(process.hrtime.bigint() - start) / 1e6; // ms
        const statusColor = getStatusColor(res.statusCode);
        const methodColor = getMethodColor(req.method);

        const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);

        const logLine = [
            `${colors.dim}${timestamp}${colors.reset}`,
            `${methodColor}${req.method.padEnd(7)}${colors.reset}`,
            `${statusColor}${res.statusCode}${colors.reset}`,
            `${req.originalUrl}`,
            `${colors.dim}${formatDuration(duration)}${colors.reset}`,
        ].join(' │ ');

        console.log(logLine);

        // Call original end
        originalEnd.apply(res, args);
    };

    next();
};

module.exports = { requestLogger };
