/**
 * AppError - Custom error class for structured error handling.
 * Generated by forge-cli
 *
 * Usage:
 *   throw new AppError('User not found', 404);
 *   throw new AppError('Validation failed', 400, { field: 'email' });
 */

class AppError extends Error {
  /**
   * @param {string} message - Error message
   * @param {number} statusCode - HTTP status code (default: 500)
   * @param {object} details - Additional error details (optional)
   */
  constructor(message, statusCode = 500, details = null) {
    super(message);
    this.name = 'AppError';
    this.statusCode = statusCode;
    this.details = details;
    this.isOperational = true;

    // Capture stack trace (excluding constructor)
    Error.captureStackTrace(this, this.constructor);
  }

  /**
   * Create a 400 Bad Request error
   */
  static badRequest(message, details) {
    return new AppError(message || 'Bad Request', 400, details);
  }

  /**
   * Create a 401 Unauthorized error
   */
  static unauthorized(message) {
    return new AppError(message || 'Unauthorized', 401);
  }

  /**
   * Create a 403 Forbidden error
   */
  static forbidden(message) {
    return new AppError(message || 'Forbidden', 403);
  }

  /**
   * Create a 404 Not Found error
   */
  static notFound(message) {
    return new AppError(message || 'Resource not found', 404);
  }

  /**
   * Create a 409 Conflict error
   */
  static conflict(message) {
    return new AppError(message || 'Conflict', 409);
  }

  /**
   * Create a 422 Unprocessable Entity error
   */
  static validation(message, details) {
    return new AppError(message || 'Validation failed', 422, details);
  }
}

module.exports = { AppError };
